### ISSUE TITLE
Sortable column is not visible

### ISSUE THREAD

**Issue by polumerk** [arogachev/yii2-sortable#20]
Добавил в конфиг приложения, добавил в бехавир модели, добавил колонку sort в таблицу, добавил код в GridView, но ни чего не появилось. Проверял убирайя id срабатывает вообще ваш код, срабатывает, выдает ошибку. Вижу что применяет к блоку стиль, но столбец не появляется. Нету документации на русском?

Мой код:

<?php Pjax::begin(); ?>

```
<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'id' => 'gov',
    'columns' => [
        [
            'class' => SortableColumn::className(),
            'gridContainerId' => 'gov',                
        ],
        ['class' => 'yii\grid\SerialColumn'],

        // 'id',
        [
            'attribute' => 'icon_site',
            'format' => 'image',    
            'value' => function ($data) {
                                            return $data->getImage()->getUrl('60x60');
                                        },
        ],
        'name_site',
        'url_site:url',

        ['class' => 'yii\grid\ActionColumn'],
    ],
]); ?>
```

<?php Pjax::end(); ?>

**Comment by polumerk** [comment]
При создании новых записей, модель в таблице поле сортировки заполняет как надо по интервалу

**Comment by arogachev** [comment]
> Добавил в конфиг приложения, добавил в бехавир модели, добавил колонку sort в таблицу, добавил код в GridView, но ни чего не появилось.

Неплохо бы добавить конфиг поведения в модели для полноты картины и лучшего понимания проблемы.

> Проверял убирайя id срабатывает вообще ваш код, срабатывает, выдает ошибку.

Не совсем понял насчет убирания id. Про ошибку - нужно больше конкретики.

> Вижу что применяет к блоку стиль, но столбец не появляется.

Сортировать можно только в пределах указанного scope и если сами записи отсортированы по колонке `sort` по возрастанию. Также учитывается право, указанное в `access`. Наверное из документации это не очень очевидно, добавлю.

Скорее всего, у вас записи не отсортированы по колонке `sort`. Я обычно делаю отдельную кнопочку-ссылку "Настройка порядка" и в ней генерируется что-то типа `?sort=sort`. Т.е. при примененном фильтре или другой сортировке можно перейти к настройке порядка. Сортировать при неверном порядке или фильтре нельзя.

> Нету документации на русском?

Пока нет. Не знаю, есть ли в ней вообще смысл, т.к. в таком виде рассчитано на международное использование, при наличии русской документации все правки нужно постоянно синхронизировать. С другой стороны, самой документации не очень много, не исключаю, что добавлю ее, как появится больше времени.

**Comment by polumerk** [comment]
Отсортировал по sort и появилась колонка для сортировки.

Проверил и получается что возможно редактировать только раз, после ответа "да" на запрос о перемещение, строка в браузере принимает вид:

```
http://site/government/index?GovernmentSiteSearch%5Bicon_site%5D=&GovernmentSiteSearch%5Bname_site%5D=&GovernmentSiteSearch%5Burl_site%5D=&sort=sort
```

и иконки управления не реагируют ни на что. в чем может быть проблема?

Есть возможность убрать подтверждение?

Согласен с вами про документацию, но тогда возможно удобно сделать вики с примером подробным. 

> Сортировать можно только в пределах указанного scope

Про scope не понял, но завтра по изучаю вопрос что такое скоуп

**Comment by arogachev** [comment]
Смотрели в консоли, что возвращает AJAX запрос?

**Comment by polumerk** [comment]
```
{"sort":{"errors":false}}
```

но отправляется смотрю два запроса, один POST:

```
Request URL:http://asr/sort/move-to-position
Request Method:POST
Status Code:200 OK
```

 второй GET:

```
Request URL:http://site/government/index?GovernmentSiteSearch%5Bicon_site%5D=&GovernmentSiteSearch%5Bname_site%5D=&GovernmentSiteSearch%5Burl_site%5D=&sort=sort&_pjax=%23w0
Request Method:GET
Status Code:200 OK
```

второй запрос возвращает html структуру таблицы.

**Comment by arogachev** [comment]
Вроде все верно. Первый - обновление, второй - PJAX. Странно, почему блокируются кнопки после первого обновления.

По поводу отмены подтверждения - согласен, неплохо бы сделать это опциональным.

Напишите мне на почту, попробуем посмотреть более детально вашу проблему (адрес можете посмотреть в composer.json как вариант).

**Comment by arogachev** [comment]
Проблема была в том, что в настройках `SortableColumn` в опции `gridContainerId` был указан `id` самого GridView, а не ближайшего неизменяемого родительского контейнера.
